# Generated by Django 4.2.4 on 2023-10-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='expurgoservidores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servidor', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='expurgo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='expurgo',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.expurgoservidores'),
        ),
        migrations.AlterUniqueTogether(
            name='expurgo',
            unique_together={('servidor', 'tabela')},
        ),
        migrations.RemoveField(
            model_name='expurgo',
            name='base',
        ),
    ]
