# Generated by Django 4.2.4 on 2023-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_expurgoservidores_alter_expurgo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expurgoservidores',
            name='is_password_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
