# Generated by Django 4.2.4 on 2023-10-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_expurgoservidores_apelido'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expurgo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='expurgo',
            name='base',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expurgo',
            unique_together={('servidor', 'base', 'tabela')},
        ),
    ]
