# Generated by Django 4.2.4 on 2023-10-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_expurgo_unique_together_expurgo_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expurgo',
            name='datahoradelete',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
