# Generated by Django 4.2.4 on 2023-10-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_expurgo_datahoradelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='expurgo',
            name='datahoratodelete',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
