# Generated by Django 4.2.4 on 2023-10-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_servidor_status_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='cpu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='disk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='memory',
            field=models.TextField(null=True),
        ),
    ]
