# Generated by Django 4.2.4 on 2023-10-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_servidor_cpu_servidor_disk_servidor_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='datahoradetalhes',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
