# Generated by Django 4.2.4 on 2023-11-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_servidor_datahoradetalhes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expurgoservidores',
            new_name='AcessoServidores',
        ),
    ]
