# Generated by Django 4.2.4 on 2023-11-10 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_expurgoservidores_acessoservidores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tamanho', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('datahora', models.DateTimeField(default=django.utils.timezone.now)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acessoservidores')),
            ],
        ),
    ]
