# Generated by Django 4.2.4 on 2023-11-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoservidores',
            name='inslots',
            field=models.BooleanField(default=False),
        ),
    ]
