# Generated by Django 4.2.4 on 2023-11-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_acessoservidores_inslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acessoservidores',
            name='base',
        ),
        migrations.AddField(
            model_name='acessoservidores',
            name='bases',
            field=models.CharField(default='postgres', max_length=255),
            preserve_default=False,
        ),
    ]
