# Generated by Django 4.2.4 on 2023-11-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_acessoservidores_base_acessoservidores_bases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='slots',
            unique_together={('servidor', 'nome')},
        ),
    ]
