# Generated by Django 4.2.4 on 2023-11-30 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_slots_nome_alter_slots_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='datahora',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 19, 49, 45, 61450, tzinfo=datetime.timezone.utc)),
        ),
    ]
